export const dataFake3 = [
  // Thế hệ 1
  {
    id: "husband1",
    gender: "male",
    parents: [],
    siblings: [],
    spouses: [
      { id: "wife1", type: "married" },
      { id: "wife2", type: "married" },
    ],
    children: [
      { id: "child1", type: "blood" },
      { id: "child2", type: "blood" },
      { id: "child3", type: "blood" },
      { id: "child6", type: "blood" },
    ],
    descendants: [
      { id: "child1", type: "blood" },
      { id: "child2", type: "blood" },
      { id: "child3", type: "blood" },
      { id: "child6", type: "blood" },
      { id: "child1kid", type: "blood" },
      { id: "child1kid2", type: "blood" },
    ],
    expanded: false,
    generationLevel: 1,
  },
  {
    id: "wife1",
    gender: "female",
    parents: [],
    siblings: [],
    spouses: [{ id: "husband1", type: "married" }],
    children: [
      { id: "child1", type: "blood" },
      { id: "child2", type: "blood" },
      { id: "child3", type: "blood" },
    ],
    descendants: [
      { id: "child1", type: "blood" },
      { id: "child2", type: "blood" },
      { id: "child3", type: "blood" },
      { id: "child1kid", type: "blood" },
      { id: "child1kid2", type: "blood" },
    ],
    expanded: false,
    generationLevel: 1,
  },
  {
    id: "wife2",
    gender: "female",
    parents: [],
    siblings: [],
    spouses: [{ id: "husband1", type: "married" }],
    children: [{ id: "child6", type: "blood" }],
    descendants: [{ id: "child6", type: "blood" }],
    expanded: false,
    generationLevel: 1,
  },

  // Thế hệ 2 (Con của husband1 với wife1 và wife2)
  {
    id: "child1",
    gender: "male",
    parents: [
      { id: "husband1", type: "blood" },
      { id: "wife1", type: "blood" },
    ],
    siblings: [],
    spouses: [{ id: "child1wife", type: "married" }],
    children: [
      { id: "child1kid", type: "blood" },
      { id: "child1kid2", type: "blood" },
    ],
    descendants: [
        { id: "child1kid", type: "blood" },
        { id: "child1kid2", type: "blood" },
      ],
    expanded: false,
    generationLevel: 2,
  },
  {
    id: "child2",
    gender: "female",
    parents: [
      { id: "husband1", type: "blood" },
      { id: "wife1", type: "blood" },
    ],
    siblings: [],
    spouses: [{ id: "child2husband", type: "married" }],
    children: [],
    expanded: false,
    generationLevel: 2,
  },
  {
    id: "child3",
    gender: "male",
    parents: [
      { id: "husband1", type: "blood" },
      { id: "wife1", type: "blood" },
    ],
    siblings: [],
    spouses: [{ id: "child3wife", type: "married" }],
    children: [],
    expanded: false,
    generationLevel: 2,
  },
  {
    id: "child6",
    gender: "male",
    parents: [
      { id: "husband1", type: "blood" },
      { id: "wife2", type: "blood" },
    ],
    siblings: [],
    spouses: [{ id: "child6wife", type: "married" }],
    children: [],
    expanded: false,
    generationLevel: 2,
  },

  // Thế hệ 2: Vợ/chồng của các con
  {
    id: "child1wife",
    gender: "female",
    parents: [],
    siblings: [],
    spouses: [{ id: "child1", type: "married" }],
    children: [],
    expanded: false,
    generationLevel: 2,
  },
  {
    id: "child2husband",
    gender: "male",
    parents: [],
    siblings: [],
    spouses: [{ id: "child2", type: "married" }],
    children: [],
    expanded: false,
    generationLevel: 2,
  },
  {
    id: "child3wife",
    gender: "female",
    parents: [],
    siblings: [],
    spouses: [{ id: "child3", type: "married" }],
    children: [],
    expanded: false,
    generationLevel: 2,
  },

  {
    id: "child6wife",
    gender: "female",
    parents: [],
    siblings: [],
    spouses: [{ id: "child6", type: "married" }],
    children: [],
    expanded: false,
    generationLevel: 2,
  },
];
